language: python

os:
  - linux
  - osx

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install pytest flake8 codecov pytest-cov
  - pip install jupyterlab nbconvert nbformat matplotlib seaborn mne
  - python setup.py sdist bdist_wheel
  - pip install --upgrade dist/*

script:
  - PYTHONPATH=. pytest --durations=0 --cov=neurolib tests
  - flake8 . --max-line-length=1000 --exit-zero

after_success:
  - codecov

jobs:
  allow_failures:
    - os: osx
  include:
    - os: osx
    addons:
      homebrew:
        update: true
        packages: python3
    before_install:
      - pip3 install virtualenv
      - virtualenv -p python3 ~/venv
      - source ~/venv/bin/activate  