language: python

os:
  - linux

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt
  - pip install --upgrade pytest
  - pip install treon flake8 codecov pytest-cov wheel setuptools jupyterlab matplotlib seaborn mne
  - python setup.py sdist bdist_wheel
  - pip install --upgrade dist/*

script:
  - PYTHONPATH=. pytest --durations=0 --cov=neurolib tests
  #- flake8 . --max-line-length=120 --exit-zero

after_success:
  - codecov

jobs:
  allow_failures:
    - os: osx
    - os: windows

  include:
    - stage: test
      os: osx
      language: sh
      addons:
        homebrew:
          update: true
          packages:
            - python3
            - llvm
            - libomp
      before_install:
        - brew link --overwrite python
        - export PATH=/usr/local/opt/llvm/bin:$PATH
        - pip3 install virtualenv
        - virtualenv -p python3 ~/venv
        - source ~/venv/bin/activate
    # - stage: test
    #   os: windows
    #   language: sh
    #   env:
    #     - PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    #   before_install:
    #     - choco install python --version 3.7.3
    #     - python -m pip install --upgrade pip
