language: python

os:
  - linux

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install pytest flake8 codecov pytest-cov
  - pip install jupyterlab nbconvert nbformat matplotlib seaborn mne
  - python setup.py sdist bdist_wheel
  - pip install --upgrade dist/*

script:
  - PYTHONPATH=. pytest --durations=0 --cov=neurolib tests
  - flake8 . --max-line-length=1000 --exit-zero

after_success:
  - codecov

jobs:
  allow_failures:
    - os: osx
    - os: windows

  include:
    - stage: test
      os: osx
      language: sh
      addons:
        homebrew:
          update: false
          packages: python3
      before_install:
        - pip install virtualenv
        - virtualenv -p python3 ~/venv
        - source ~/venv/bin/activate

    - stage: test
      os: windows
      language: sh
      env:
        - PATH="/c/Python37:/c/Python37/Scripts:$PATH"
      before_cache: rm -f "$LOCALAPPDATA/pip/Cache/log/debug.log"
      cache:
        directories: "$LOCALAPPDATA/pip/Cache"
      addons:
        chocolatey:
          update: false
          packages: python3
      before_install: 
        - choco install -y python
        - python -m pip install -U pip
