language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - python setup.py sdist bdist_wheel
  - pip install --upgrade dist/*

script:
  - pytest tests/
  - python tests/test.py
  - flake8 . --exit-zero
