language: python

python:
  - "3.7"
  
install:
  - pip install -r requirements.txt
  - pip install pytest flake8
  - pip install jupyterlab nbconvert nbformat matplotlib seaborn
  - python setup.py sdist bdist_wheel
  - pip install --upgrade dist/*

script:
  - pytest --durations=0 tests/
  - flake8 . --max-line-length=1000 --exit-zero
