coverage:
  precision: 2
  round: nearest
  range: "90...100"
  threshold: 3%
  ignore:
    - "neurolib/models/**/timeIntegration.py" 
	- "neurolib/models/aln/timeIntegration.py" 
	- "neurolib/models/fhn/timeIntegration.py" 
	- "neurolib/models/hopf/timeIntegration.py" 
	- "neurolib/models/wc/timeIntegration.py" 
	- "neurolib/models/thalamus/timeIntegration.py" 
	- "neurolib/models/bold/timeIntegration.py" 
	- "neurolib/utils/devUtils.py"
  status:
    patch: off