coverage:
  precision: 2
  round: nearest
  range: "80...100"
  ignore:
    - "neurolib/models/**/timeIntegration.py" 
    - "neurolib/utils/devUtils.py"
    - "neurolib/utils/atlases.py"
  status:
    patch: off